---  # GiHub action workflow for CI pre-commit builds
name: Build on Linux
on:
  push:
    branches:
      - trunk
  pull_request:

jobs:
  build-linux:
    name: Build using GCC 9 (or later) on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Clone Source
        uses: actions/checkout@v2
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
      - name: Create Build Directory
        run:  mkdir build
      - name: Configure
        run:  cd build && cmake --version && cmake -DCMAKE_VERBOSE_MAKEFILE=ON ..
        env:
          CC: gcc-9
          CXX: g++-9
      - name: Build
        run:  cd build && cmake --build .
      - name: Test
        run:  cd build && ctest --verbose

