---  # GiHub action workflow for CI pre-commit builds
name: Build on Windows
on:
  push:
  pull_request:
    branches: trunk

jobs:
  build-windows:
    name: Build using MSVC 2017 (or later) on Microsoft Windows
    runs-on: windows-latest
    steps:
      - name: Clone Source
        uses: actions/checkout@v2
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
      - name: Create Build Directory
        run:  mkdir build
      - name: Configure
        run:  cd build && cmake -DCMAKE_VERBOSE_MAKEFILE=ON -Dqt=on ..
      - name: Build
        run:  cd build && cmake --build .
